# -*- coding: utf-8 -*-
"""DotsAndBoxesIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sq1fK4yjlX_rrVE_vwq9oJvX07ELr1Hg
"""

# Función para verificar si todas las posiciones están ocupadas
def todas_posiciones_ocupadas(tablero):
    for fila in tablero:
        for celda in fila:
            if celda == '0':
                return False
    return True

# Función para dibujar el tablero
def dibujar_tablero(tablero):
    for fila in tablero:
        print("".join(fila))

# Función para dibujar una línea en la posición dada
def dibujar_linea(tablero, fila, columna):
    if fila % 2 == 0:
        tablero[fila][columna] = "-"
    else:
        tablero[fila][columna] = "|"

# Crear un tablero representado como una lista de listas
tablero = []
for i in range(7):
    if i % 2 == 0:
        tablero.append(['+  ', '0', '  +  ', '0', '  +  ', '0', '  +'])
    else:
        tablero.append(['0', '     ', '0', '     ', '0', '     ', '0'])

# Dibujar el tablero inicial
dibujar_tablero(tablero)

# Continuar hasta que todas las posiciones estén ocupadas
while not todas_posiciones_ocupadas(tablero):
    # Solicitar al usuario que ingrese la fila y la columna
    fila = int(input("\nIngrese la fila (0-6): "))
    columna = int(input("Ingrese la columna (0-6): "))

    # Verificar si la posición seleccionada es válida y dibujar la línea
    if fila >= 0 and fila < 7 and columna >= 0 and columna < 7 and tablero[fila][columna] == "0":
        dibujar_linea(tablero, fila, columna)
        print("\nTablero actualizado:")
        dibujar_tablero(tablero)
    else:
        print("Posición inválida o ya ocupada.")

print("¡Todas las posiciones han sido ocupadas!")